project:
  type: website

website:
  title: "Sadichchha Shrestha"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: about.qmd
        text: About
      - href: teaching.qmd
        text: Teaching
      - href: files/Sadichchha_Shrestha_CV.pdf
        text: CV
    right:
      - href: "https://scholar.google.com/"
        text: Google Scholar

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: false

editor: visual