project:
  type: website

website:
  title: "Sadichchha Shrestha"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      # - href: about.qmd
      #   text: About
      - href: "https://www.nepalstock.com/"
        text: CV

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: false

editor: visual